package utils

import (
	"fmt"
	"image"
	"image/color"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/disintegration/imaging"
)

const (
	DefaultThumbnailWidth  = 300
	DefaultThumbnailHeight = 169
	ThumbnailQuality       = 85
)

// GenerateThumbnail generates a thumbnail for an image file.
func GenerateThumbnail(filePath, outputPath string, width, height int) error {
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		return fmt.Errorf("source file does not exist: %s", filePath)
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	src, err := imaging.Open(filePath)
	if err != nil {
		return fmt.Errorf("failed to open source image: %w", err)
	}

	dst := imaging.Fill(src, width, height, imaging.Center, imaging.Lanczos)

	switch strings.ToLower(filepath.Ext(outputPath)) {
	case ".jpg", ".jpeg":
		return imaging.Save(dst, outputPath, imaging.JPEGQuality(ThumbnailQuality))
	default:
		return imaging.Save(dst, outputPath)
	}
}

// GenerateVideoThumbnail generates a thumbnail from a video frame.
func GenerateVideoThumbnail(filePath, outputPath string, width, height int) error {
	if !isFFmpegAvailable() {
		return fmt.Errorf("ffmpeg is not available on the system")
	}
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		return fmt.Errorf("source file does not exist: %s", filePath)
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	cmd := exec.Command("ffmpeg",
		"-i", filePath,
		"-ss", "00:00:01",
		"-vframes", "1",
		"-vf", fmt.Sprintf("scale=%d:%d:force_original_aspect_ratio=increase,crop=%d:%d", width, height, width, height),
		"-f", "image2",
		"-update", "1",
		"-y",
		outputPath,
	)

	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to generate video thumbnail: %w: %s", err, strings.TrimSpace(string(output)))
	}

	return nil
}

// GenerateDocumentThumbnail is kept for API compatibility.
// Document previews are intentionally not generated by the application.
func GenerateDocumentThumbnail(filePath, outputPath string, width, height int) error {
	return fmt.Errorf("document thumbnails are not supported")
}

// GenerateAudioThumbnail is kept for API compatibility.
// Audio previews are intentionally not generated by the application.
func GenerateAudioThumbnail(filePath, outputPath string, width, height int) error {
	return fmt.Errorf("audio thumbnails are not supported")
}

// GeneratePlaceholderThumbnail generates a generic placeholder image.
func GeneratePlaceholderThumbnail(outputPath string, width, height int) error {
	img := image.NewRGBA(image.Rect(0, 0, width, height))
	for y := 0; y < height; y++ {
		for x := 0; x < width; x++ {
			img.SetRGBA(x, y, color.RGBA{240, 240, 240, 255})
		}
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	return imaging.Save(img, outputPath)
}

// IsThumbnailSupported reports whether a file has a real visual preview.
func IsThumbnailSupported(filePath string) bool {
	ext := strings.ToLower(filepath.Ext(filePath))
	supportedFormats := []string{
		".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp",
		".mp4", ".avi", ".mkv", ".mov", ".wmv", ".flv", ".webm", ".m4v",
	}

	for _, format := range supportedFormats {
		if ext == format {
			return true
		}
	}

	return false
}

func GetThumbnailFileType(originalPath string) string {
	return "png"
}

// GenerateThumbnailForFile generates a thumbnail for image or video files.
func GenerateThumbnailForFile(filePath, fileType string) (string, error) {
	if !IsThumbnailSupported(filePath) {
		return "", fmt.Errorf("unsupported file type for thumbnail generation")
	}

	cacheKey := generateCacheKey(filePath)
	outputDir := filepath.Join(os.TempDir(), "localspace", "thumbnails")
	outputPath := filepath.Join(outputDir, cacheKey+".png")

	if _, err := os.Stat(outputPath); err == nil {
		return outputPath, nil
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create cache directory: %w", err)
	}

	var err error
	switch fileType {
	case "image":
		err = GenerateThumbnail(filePath, outputPath, DefaultThumbnailWidth, DefaultThumbnailHeight)
	case "video":
		err = GenerateVideoThumbnail(filePath, outputPath, DefaultThumbnailWidth, DefaultThumbnailHeight)
	default:
		return "", fmt.Errorf("unsupported file type for thumbnail generation")
	}

	if err != nil {
		return "", fmt.Errorf("failed to generate thumbnail: %w", err)
	}

	return outputPath, nil
}

func ClearThumbnailCache() error {
	cacheDir := filepath.Join(os.TempDir(), "localspace", "thumbnails")
	return os.RemoveAll(cacheDir)
}

func GetThumbnailCacheSize() (int64, error) {
	cacheDir := filepath.Join(os.TempDir(), "localspace", "thumbnails")
	return getDirSize(cacheDir)
}

func generateCacheKey(filePath string) string {
	return strings.ReplaceAll(strings.ReplaceAll(filePath, "/", "_"), "\\", "_")
}

func getDirSize(path string) (int64, error) {
	var size int64
	err := filepath.Walk(path, func(_ string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			size += info.Size()
		}
		return nil
	})
	return size, err
}

func isFFmpegAvailable() bool {
	cmd := exec.Command("ffmpeg", "-version")
	return cmd.Run() == nil
}

func GetThumbnailQuality() int {
	return ThumbnailQuality
}

func SetThumbnailQuality(quality int) error {
	if quality < 1 || quality > 100 {
		return fmt.Errorf("quality must be between 1 and 100")
	}
	return nil
}
