// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1) {
  return window['go']['app']['App']['AddCollection'](arg1);
}

export function AddMasterDirectory(arg1, arg2) {
  return window['go']['app']['App']['AddMasterDirectory'](arg1, arg2);
}

export function AddStorageDirectory(arg1, arg2) {
  return window['go']['app']['App']['AddStorageDirectory'](arg1, arg2);
}

export function ApplyConfirmedAIAnalysis(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ApplyConfirmedAIAnalysis'](arg1, arg2, arg3, arg4);
}

export function BatchDeleteFiles(arg1) {
  return window['go']['app']['App']['BatchDeleteFiles'](arg1);
}

export function BatchUpdateFilesCollection(arg1, arg2) {
  return window['go']['app']['App']['BatchUpdateFilesCollection'](arg1, arg2);
}

export function CancelJob(arg1) {
  return window['go']['app']['App']['CancelJob'](arg1);
}

export function CheckDuplicate(arg1) {
  return window['go']['app']['App']['CheckDuplicate'](arg1);
}

export function CheckMasterStorageSpace(arg1, arg2) {
  return window['go']['app']['App']['CheckMasterStorageSpace'](arg1, arg2);
}

export function CheckPathConflict(arg1, arg2) {
  return window['go']['app']['App']['CheckPathConflict'](arg1, arg2);
}

export function CheckStorageSpace(arg1) {
  return window['go']['app']['App']['CheckStorageSpace'](arg1);
}

export function ClearThumbnailCache() {
  return window['go']['app']['App']['ClearThumbnailCache']();
}

export function ConfirmQuit() {
  return window['go']['app']['App']['ConfirmQuit']();
}

export function DeleteFile(arg1) {
  return window['go']['app']['App']['DeleteFile'](arg1);
}

export function DeleteJobRecord(arg1) {
  return window['go']['app']['App']['DeleteJobRecord'](arg1);
}

export function GenerateThumbnail(arg1) {
  return window['go']['app']['App']['GenerateThumbnail'](arg1);
}

export function GetAIAnalysis(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetAIAnalysis'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAIConfig() {
  return window['go']['app']['App']['GetAIConfig']();
}

export function GetActiveJobs() {
  return window['go']['app']['App']['GetActiveJobs']();
}

export function GetBatchImportItems(arg1) {
  return window['go']['app']['App']['GetBatchImportItems'](arg1);
}

export function GetCollectionFilterCounts(arg1) {
  return window['go']['app']['App']['GetCollectionFilterCounts'](arg1);
}

export function GetCollections() {
  return window['go']['app']['App']['GetCollections']();
}

export function GetConfig(arg1) {
  return window['go']['app']['App']['GetConfig'](arg1);
}

export function GetDuplicateFiles() {
  return window['go']['app']['App']['GetDuplicateFiles']();
}

export function GetExitGuardSnapshot() {
  return window['go']['app']['App']['GetExitGuardSnapshot']();
}

export function GetFile(arg1) {
  return window['go']['app']['App']['GetFile'](arg1);
}

export function GetFileMetadata(arg1, arg2) {
  return window['go']['app']['App']['GetFileMetadata'](arg1, arg2);
}

export function GetFileTypes() {
  return window['go']['app']['App']['GetFileTypes']();
}

export function GetFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetFiles'](arg1, arg2, arg3, arg4);
}

export function GetJob(arg1) {
  return window['go']['app']['App']['GetJob'](arg1);
}

export function GetJobRetentionConfig() {
  return window['go']['app']['App']['GetJobRetentionConfig']();
}

export function GetMasterDirectories() {
  return window['go']['app']['App']['GetMasterDirectories']();
}

export function GetMasterStoragePathForFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetMasterStoragePathForFile'](arg1, arg2, arg3, arg4);
}

export function GetOpenWithConfig() {
  return window['go']['app']['App']['GetOpenWithConfig']();
}

export function GetResumableJobs() {
  return window['go']['app']['App']['GetResumableJobs']();
}

export function GetStorageDirectories() {
  return window['go']['app']['App']['GetStorageDirectories']();
}

export function GetStorageLayoutConfig() {
  return window['go']['app']['App']['GetStorageLayoutConfig']();
}

export function GetThemeConfig() {
  return window['go']['app']['App']['GetThemeConfig']();
}

export function GetThumbnailCacheInfo() {
  return window['go']['app']['App']['GetThumbnailCacheInfo']();
}

export function GetThumbnailCacheStats() {
  return window['go']['app']['App']['GetThumbnailCacheStats']();
}

export function ImportFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ImportFile'](arg1, arg2, arg3, arg4);
}

export function ImportFileWithKeywords(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ImportFileWithKeywords'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportFileWithMetadata(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['ImportFileWithMetadata'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InitConfig(arg1) {
  return window['go']['app']['App']['InitConfig'](arg1);
}

export function ListJobs(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListJobs'](arg1, arg2, arg3);
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['app']['App']['OpenFileLocation'](arg1);
}

export function OpenFileWithPreferredApp(arg1) {
  return window['go']['app']['App']['OpenFileWithPreferredApp'](arg1);
}

export function OpenFileWithSystemDefault(arg1) {
  return window['go']['app']['App']['OpenFileWithSystemDefault'](arg1);
}

export function ParseFileType(arg1) {
  return window['go']['app']['App']['ParseFileType'](arg1);
}

export function RefreshFile(arg1) {
  return window['go']['app']['App']['RefreshFile'](arg1);
}

export function RemoveCollection(arg1) {
  return window['go']['app']['App']['RemoveCollection'](arg1);
}

export function RemoveStorageDirectory(arg1) {
  return window['go']['app']['App']['RemoveStorageDirectory'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['app']['App']['RenameFile'](arg1, arg2);
}

export function RequestQuit() {
  return window['go']['app']['App']['RequestQuit']();
}

export function ResumeJob(arg1) {
  return window['go']['app']['App']['ResumeJob'](arg1);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectExecutable() {
  return window['go']['app']['App']['SelectExecutable']();
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}

export function SelectFiles() {
  return window['go']['app']['App']['SelectFiles']();
}

export function SetDefaultMasterDirectory(arg1) {
  return window['go']['app']['App']['SetDefaultMasterDirectory'](arg1);
}

export function SubmitBatchImportJob(arg1) {
  return window['go']['app']['App']['SubmitBatchImportJob'](arg1);
}

export function SubmitJobCleanup() {
  return window['go']['app']['App']['SubmitJobCleanup']();
}

export function SubmitSingleImportJob(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['SubmitSingleImportJob'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ToggleStorageDirectory(arg1, arg2) {
  return window['go']['app']['App']['ToggleStorageDirectory'](arg1, arg2);
}

export function UpdateAIConfig(arg1) {
  return window['go']['app']['App']['UpdateAIConfig'](arg1);
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['app']['App']['UpdateConfig'](arg1, arg2);
}

export function UpdateFileMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateFileMetadata'](arg1, arg2, arg3, arg4);
}

export function UpdateJobRetentionConfig(arg1) {
  return window['go']['app']['App']['UpdateJobRetentionConfig'](arg1);
}

export function UpdateOpenWithConfig(arg1) {
  return window['go']['app']['App']['UpdateOpenWithConfig'](arg1);
}

export function UpdateStorageLayoutConfig(arg1) {
  return window['go']['app']['App']['UpdateStorageLayoutConfig'](arg1);
}

export function UpdateThemeConfig(arg1) {
  return window['go']['app']['App']['UpdateThemeConfig'](arg1);
}
