// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddCollection(arg1:string):Promise<number>;

export function AddMasterDirectory(arg1:string,arg2:number):Promise<void>;

export function AddStorageDirectory(arg1:string,arg2:string):Promise<void>;

export function BatchDeleteFiles(arg1:Array<number>):Promise<models.BatchDeleteResult>;

export function BatchUpdateFilesCollection(arg1:Array<number>,arg2:number):Promise<models.BatchMoveResult>;

export function CancelJob(arg1:number):Promise<void>;

export function CheckDuplicate(arg1:string):Promise<Record<string, any>>;

export function CheckMasterStorageSpace(arg1:number,arg2:number):Promise<boolean>;

export function CheckPathConflict(arg1:string,arg2:number):Promise<boolean>;

export function CheckStorageSpace(arg1:number):Promise<boolean>;

export function ClearThumbnailCache():Promise<void>;

export function DeleteFile(arg1:number):Promise<void>;

export function DeleteJobRecord(arg1:number):Promise<void>;

export function GenerateThumbnail(arg1:number):Promise<string>;

export function GetAIAnalysis(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<models.AIAnalysis>;

export function GetAIConfig():Promise<models.AIConfig>;

export function GetActiveJobs():Promise<Array<models.Job>>;

export function GetCollectionFilterCounts(arg1:string):Promise<models.CollectionFilterCounts>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDuplicateFiles():Promise<Record<string, Array<Record<string, any>>>>;

export function GetFile(arg1:number):Promise<models.File>;

export function GetFileMetadata(arg1:string,arg2:string):Promise<models.Metadata>;

export function GetFileTypes():Promise<Array<models.FileType>>;

export function GetFiles(arg1:number,arg2:number,arg3:string,arg4:number):Promise<models.FileListResponse>;

export function GetJob(arg1:number):Promise<models.Job>;

export function GetJobRetentionConfig():Promise<models.JobRetentionConfig>;

export function GetMasterDirectories():Promise<Array<models.StorageDir>>;

export function GetMasterStoragePathForFile(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetOpenWithConfig():Promise<models.OpenWithConfig>;

export function GetResumableJobs():Promise<Array<models.Job>>;

export function GetStorageDirectories():Promise<Array<models.StorageDir>>;

export function GetStorageLayoutConfig():Promise<models.StorageLayoutConfig>;

export function GetThemeConfig():Promise<models.ThemeConfig>;

export function GetThumbnailCacheInfo():Promise<number>;

export function GetThumbnailCacheStats():Promise<Record<string, any>>;

export function ImportFile(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function ImportFileWithKeywords(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<void>;

export function ImportFileWithMetadata(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:number):Promise<void>;

export function InitConfig(arg1:string):Promise<void>;

export function ListJobs(arg1:number,arg2:number,arg3:string):Promise<models.JobListResponse>;

export function OpenFile(arg1:number):Promise<void>;

export function OpenFileLocation(arg1:number):Promise<void>;

export function OpenFileWithPreferredApp(arg1:number):Promise<void>;

export function OpenFileWithSystemDefault(arg1:number):Promise<void>;

export function ParseFileType(arg1:string):Promise<models.FileType>;

export function RefreshFile(arg1:number):Promise<models.File>;

export function RemoveCollection(arg1:number):Promise<void>;

export function RemoveStorageDirectory(arg1:number):Promise<void>;

export function RenameFile(arg1:number,arg2:string):Promise<void>;

export function ResumeJob(arg1:number):Promise<void>;

export function SearchFiles(arg1:string,arg2:number,arg3:number):Promise<models.FileListResponse>;

export function SelectDirectory():Promise<string>;

export function SelectExecutable():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFiles():Promise<Array<models.SelectedFile>>;

export function SetDefaultMasterDirectory(arg1:number):Promise<void>;

export function SubmitBatchImportJob(arg1:models.BatchImportJobRequest):Promise<models.Job>;

export function SubmitJobCleanup():Promise<models.Job>;

export function SubmitSingleImportJob(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:number):Promise<models.Job>;

export function ToggleStorageDirectory(arg1:number,arg2:boolean):Promise<void>;

export function UpdateAIConfig(arg1:models.AIConfig):Promise<void>;

export function UpdateConfig(arg1:string,arg2:string):Promise<void>;

export function UpdateFileMetadata(arg1:number,arg2:Array<string>,arg3:string,arg4:number):Promise<void>;

export function UpdateJobRetentionConfig(arg1:models.JobRetentionConfig):Promise<void>;

export function UpdateOpenWithConfig(arg1:models.OpenWithConfig):Promise<void>;

export function UpdateStorageLayoutConfig(arg1:models.StorageLayoutConfig):Promise<void>;

export function UpdateThemeConfig(arg1:models.ThemeConfig):Promise<void>;
