// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddMasterDirectory(arg1:string,arg2:number):Promise<void>;

export function AddStorageDirectory(arg1:string,arg2:string):Promise<void>;

export function CheckDuplicate(arg1:string):Promise<Record<string, any>>;

export function CheckMasterStorageSpace(arg1:number,arg2:number):Promise<boolean>;

export function CheckPathConflict(arg1:string,arg2:number):Promise<boolean>;

export function CheckStorageSpace(arg1:number):Promise<boolean>;

export function ClearThumbnailCache():Promise<void>;

export function DeleteFile(arg1:number):Promise<void>;

export function GenerateThumbnail(arg1:number):Promise<string>;

export function GetAIAnalysis(arg1:string,arg2:string):Promise<models.AIAnalysis>;

export function GetAIConfig():Promise<models.AIConfig>;

export function GetConfig(arg1:string):Promise<string>;

export function GetDuplicateFiles():Promise<Record<string, Array<Record<string, any>>>>;

export function GetFile(arg1:number):Promise<models.File>;

export function GetFileMetadata(arg1:string,arg2:string):Promise<models.Metadata>;

export function GetFileTypes():Promise<Array<models.FileType>>;

export function GetFiles(arg1:number,arg2:number,arg3:string):Promise<Array<models.File>>;

export function GetMasterDirectories():Promise<Array<models.StorageDir>>;

export function GetMasterStoragePathForFile(arg1:number,arg2:string,arg3:string):Promise<string>;

export function GetStorageDirectories():Promise<Array<models.StorageDir>>;

export function GetThemeConfig():Promise<models.ThemeConfig>;

export function GetThumbnailCacheInfo():Promise<number>;

export function GetThumbnailCacheStats():Promise<Record<string, any>>;

export function ImportFile(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function InitConfig(arg1:string):Promise<void>;

export function OpenFile(arg1:number):Promise<void>;

export function OpenFileLocation(arg1:number):Promise<void>;

export function ParseFileType(arg1:string):Promise<models.FileType>;

export function RefreshFile(arg1:number):Promise<models.File>;

export function RemoveStorageDirectory(arg1:number):Promise<void>;

export function RenameFile(arg1:number,arg2:string):Promise<void>;

export function SearchFiles(arg1:string):Promise<Array<models.File>>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SetDefaultMasterDirectory(arg1:number):Promise<void>;

export function ToggleStorageDirectory(arg1:number,arg2:boolean):Promise<void>;

export function UpdateAIConfig(arg1:models.AIConfig):Promise<void>;

export function UpdateConfig(arg1:string,arg2:string):Promise<void>;

export function UpdateThemeConfig(arg1:models.ThemeConfig):Promise<void>;
